"""
This file is generated by the sympycore/arithmetic/mk_methods.py script.
DO NOT CHANGE THIS FILE DIRECTLY!!!
"""

from .numbers import Complex, Float, FractionTuple, realtypes




def complex_add(self, other, new=object.__new__, cls=Complex):
    t = type(other)
    if t is int or t is long or t is FractionTuple or t is float or t is Float:
        #ADD_COMPLEX_REAL(LHS=self; RHS=other)
        #RETURN_COMPLEX(REAL=self.real + other; IMAG=self.imag)
        _tmp3 = new(cls)
        _tmp3.real = self.real + other
        _tmp3.imag = self.imag
        return _tmp3
    if t is cls or t is complex:
        #ADD_COMPLEX_COMPLEX(LHS=self; RHS=other)
        #RETURN_COMPLEX2(REAL=self.real + other.real; IMAG=self.imag + other.imag)
        _tmp5 = self.imag + other.imag
        if not _tmp5:
            return self.real + other.real
        #RETURN_COMPLEX(REAL=self.real + other.real; IMAG=_tmp5)
        _tmp6 = new(cls)
        _tmp6.real = self.real + other.real
        _tmp6.imag = _tmp5
        return _tmp6
    return NotImplemented

    
