"""
Generated arithmetic methods for numbers.

This file is generated by the src/mk_numbers_methods.py script.
See http://sympycore.googlecode.com/ for more information.

DO NOT CHANGE THIS FILE DIRECTLY!!!
"""

from .numbers import mpqc, mpf, mpq, mpc, inttypes_set, realtypes_set, complextypes_set, numbertypes_set



def fraction_add(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #ADD_FRACTION_INT(LHS=self; RHS=other)
        p, q = self
        #RETURN_FRACTION(NUMER=p+q*(other); DENOM=q)
        return cls((p+q*(other), q))
    elif t is cls:
        #ADD_FRACTION_FRACTION(LHS=self; RHS=other)
        #ADDOP_FRACTION_FRACTION(LHS=self; RHS=other; SIGN=+; MOD=%)
        p, q = self
        r, s = other
        _tmp30 = p*s + q*r
        if not _tmp30:
            return 0
        #RETURN_FRACTION2(NUMER=_tmp30; DENOM=q*s; MOD=%)
        #FRACTION_NORMALIZE(NUMER=_tmp30; DENOM=q*s; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = _tmp30
        _q = _y = q*s
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    return NotImplemented

def fraction_sub(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #SUB_FRACTION_INT(LHS=self; RHS=other)
        p, q = self
        #RETURN_FRACTION(NUMER=p-q*(other); DENOM=q)
        return cls((p-q*(other), q))
    elif t is cls:
        #SUB_FRACTION_FRACTION(LHS=self; RHS=other)
        #ADDOP_FRACTION_FRACTION(LHS=self; RHS=other; SIGN=-; MOD=%)
        p, q = self
        r, s = other
        _tmp86 = p*s - q*r
        if not _tmp86:
            return 0
        #RETURN_FRACTION2(NUMER=_tmp86; DENOM=q*s; MOD=%)
        #FRACTION_NORMALIZE(NUMER=_tmp86; DENOM=q*s; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = _tmp86
        _q = _y = q*s
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    return NotImplemented

def fraction_rsub(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #SUB_INT_FRACTION(RHS=self; LHS=other)
        p, q = self
        #RETURN_FRACTION(NUMER=q*(other) - p; DENOM=q)
        return cls((q*(other) - p, q))
    return NotImplemented

def fraction_mul(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #MUL_FRACTION_INT(LHS=self; RHS=other; MOD=%)
        p, q = self
        #RETURN_FRACTION2(NUMER=p*other; DENOM=q; MOD=%)
        #FRACTION_NORMALIZE(NUMER=p*other; DENOM=q; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = p*other
        _q = _y = q
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    elif t is cls:
        #MUL_FRACTION_FRACTION(LHS=self; RHS=other; MOD=%)
        p, q = self
        r, s = other
        #RETURN_FRACTION2(NUMER=p*r; DENOM=q*s; MOD=%)
        #FRACTION_NORMALIZE(NUMER=p*r; DENOM=q*s; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = p*r
        _q = _y = q*s
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    return NotImplemented

def fraction_div(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #DIV_FRACTION_INT(LHS=self; RHS=other; MOD=%)
        p, q = self
        #RETURN_FRACTION2(NUMER=p; DENOM=q*other; MOD=%)
        #FRACTION_NORMALIZE(NUMER=p; DENOM=q*other; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = p
        _q = _y = q*other
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    elif t is cls:
        #DIV_FRACTION_FRACTION(LHS=self; RHS=other; MOD=%)
        p, q = self
        r, s = other
        #RETURN_FRACTION2(NUMER=p*s; DENOM=q*r; MOD=%)
        #FRACTION_NORMALIZE(NUMER=p*s; DENOM=q*r; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = p*s
        _q = _y = q*r
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    return NotImplemented

def fraction_rdiv(self, other, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        #DIV_INT_FRACTION(RHS=self; LHS=other; MOD=%)
        p, q = self
        #RETURN_FRACTION2(NUMER=other*q; DENOM=p; MOD=%)
        #FRACTION_NORMALIZE(NUMER=other*q; DENOM=p; RNUMER=_p; RDENOM=_q; MOD=%)
        _p = _x = other*q
        _q = _y = p
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            _p //= _x
            _q //= _x
        if _q == 1:
            return _p
        #RETURN_FRACTION(NUMER=_p; DENOM=_q)
        return cls((_p, _q))
    return NotImplemented

def fraction_pow(self, other, m=None, cls=mpq):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        if not other:
            return 1
        if other==1:
            return self
        #POW_FRACTION_INT(LHS=self; RHS=other)
        _tmp303 = other
        p, q = self
        if _tmp303 > 0:
            #RETURN_FRACTION(NUMER=p**_tmp303; DENOM=q**_tmp303)
            return cls((p**_tmp303, q**_tmp303))
        _tmp303 = -_tmp303
        if p > 0:
            #RETURN_FRACTION(NUMER=q**_tmp303; DENOM=p**_tmp303)
            return cls((q**_tmp303, p**_tmp303))
        #RETURN_FRACTION(NUMER=(-q)**_tmp303; DENOM=(-p)**_tmp303)
        return cls(((-q)**_tmp303, (-p)**_tmp303))
    return NotImplemented

def complex_add(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #ADD_COMPLEX_REAL(LHS=self; RHS=other)
        #RETURN_COMPLEX(REAL=self.real + other; IMAG=self.imag)
        _tmp345 = new(cls)
        _tmp345.real = self.real + other
        _tmp345.imag = self.imag
        return _tmp345
    #IF_CHECK_COMPLEX(T=t)
    if t in complextypes_set:
        #ADD_COMPLEX_COMPLEX(LHS=self; RHS=other)
        #RETURN_COMPLEX2(REAL=self.real + other.real; IMAG=self.imag + other.imag)
        _tmp366 = self.imag + other.imag
        if not _tmp366:
            return self.real + other.real
        #RETURN_COMPLEX(REAL=self.real + other.real; IMAG=_tmp366)
        _tmp373 = new(cls)
        _tmp373.real = self.real + other.real
        _tmp373.imag = _tmp366
        return _tmp373
    return NotImplemented

def complex_sub(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #SUB_COMPLEX_REAL(LHS=self; RHS=other)
        #RETURN_COMPLEX(REAL=self.real - other; IMAG=self.imag)
        _tmp394 = new(cls)
        _tmp394.real = self.real - other
        _tmp394.imag = self.imag
        return _tmp394
    #IF_CHECK_COMPLEX(T=t)
    if t in complextypes_set:
        #SUB_COMPLEX_COMPLEX(LHS=self; RHS=other)
        #RETURN_COMPLEX2(REAL=self.real - other.real; IMAG=self.imag - other.imag)
        _tmp415 = self.imag - other.imag
        if not _tmp415:
            return self.real - other.real
        #RETURN_COMPLEX(REAL=self.real - other.real; IMAG=_tmp415)
        _tmp422 = new(cls)
        _tmp422.real = self.real - other.real
        _tmp422.imag = _tmp415
        return _tmp422
    return NotImplemented

def complex_rsub(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #SUB_REAL_COMPLEX(LHS=other; RHS=self)
        #RETURN_COMPLEX(REAL=other - self.real; IMAG=-self.imag)
        _tmp443 = new(cls)
        _tmp443.real = other - self.real
        _tmp443.imag = -self.imag
        return _tmp443
    if t is complex:
        #SUB_COMPLEX_COMPLEX(LHS=other; RHS=self)
        #RETURN_COMPLEX2(REAL=other.real - self.real; IMAG=other.imag - self.imag)
        _tmp457 = other.imag - self.imag
        if not _tmp457:
            return other.real - self.real
        #RETURN_COMPLEX(REAL=other.real - self.real; IMAG=_tmp457)
        _tmp464 = new(cls)
        _tmp464.real = other.real - self.real
        _tmp464.imag = _tmp457
        return _tmp464
    return NotImplemented

def complex_mul(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #MUL_COMPLEX_REAL(LHS=self; RHS=other)
        #RETURN_COMPLEX2(REAL=self.real*other; IMAG=self.imag*other)
        _tmp485 = self.imag*other
        if not _tmp485:
            return self.real*other
        #RETURN_COMPLEX(REAL=self.real*other; IMAG=_tmp485)
        _tmp492 = new(cls)
        _tmp492.real = self.real*other
        _tmp492.imag = _tmp485
        return _tmp492
    #IF_CHECK_COMPLEX(T=t)
    if t in complextypes_set:
        #MUL_COMPLEX_COMPLEX(LHS=self; RHS=other)
        a, b = self.real, self.imag
        c, d = other.real, other.imag
        #RETURN_COMPLEX2(REAL=a*c-b*d; IMAG=b*c+a*d)
        _tmp513 = b*c+a*d
        if not _tmp513:
            return a*c-b*d
        #RETURN_COMPLEX(REAL=a*c-b*d; IMAG=_tmp513)
        _tmp520 = new(cls)
        _tmp520.real = a*c-b*d
        _tmp520.imag = _tmp513
        return _tmp520
    return NotImplemented

def complex_div(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #DIV_COMPLEX_REAL(LHS=self; RHS=other; MOD=%)
        #DIV_VALUE_VALUE(LHS=self.real; RHS=other; RESULT=re; MOD=%)
        _p, _q = self.real, other
        if not _q:
            raise ZeroDivisionError(repr(self.real) + " / " + repr(other))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                re = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                re = _p / _q
        else:
            re = _p / _q
        #DIV_VALUE_VALUE(LHS=self.imag; RHS=other; RESULT=im; MOD=%)
        _p, _q = self.imag, other
        if not _q:
            raise ZeroDivisionError(repr(self.imag) + " / " + repr(other))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                im = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                im = _p / _q
        else:
            im = _p / _q
        #RETURN_COMPLEX(REAL=re; IMAG=im)
        _tmp597 = new(cls)
        _tmp597.real = re
        _tmp597.imag = im
        return _tmp597
    #IF_CHECK_COMPLEX(T=t)
    if t in complextypes_set:
        #DIV_COMPLEX_COMPLEX(LHS=self; RHS=other; MOD=%)
        a, b = self.real, self.imag
        c, d = other.real, other.imag
        mag = c*c + d*d
        _tmp611 = b*c-a*d
        #DIV_VALUE_VALUE(LHS=a*c+b*d; RHS=mag; RESULT=re; MOD=%)
        _p, _q = a*c+b*d, mag
        if not _q:
            raise ZeroDivisionError(repr(a*c+b*d) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                re = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                re = _p / _q
        else:
            re = _p / _q
        if not _tmp611:
            return re
        #DIV_VALUE_VALUE(LHS=_tmp611; RHS=mag; RESULT=im; MOD=%)
        _p, _q = _tmp611, mag
        if not _q:
            raise ZeroDivisionError(repr(_tmp611) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                im = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                im = _p / _q
        else:
            im = _p / _q
        #RETURN_COMPLEX(REAL=re; IMAG=im)
        _tmp674 = new(cls)
        _tmp674.real = re
        _tmp674.imag = im
        return _tmp674
    return NotImplemented

def complex_rdiv(self, other, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_REAL(T=t)
    if t in realtypes_set:
        #DIV_REAL_COMPLEX(LHS=other; RHS=self; MOD=%)
        _tmp688 = other
        c, d = self.real, self.imag
        mag = c*c + d*d
        #DIV_VALUE_VALUE(LHS=-_tmp688*d; RHS=mag; RESULT=im; MOD=%)
        _p, _q = -_tmp688*d, mag
        if not _q:
            raise ZeroDivisionError(repr(-_tmp688*d) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                im = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                im = _p / _q
        else:
            im = _p / _q
        #DIV_VALUE_VALUE(LHS= _tmp688*c; RHS=mag; RESULT=re; MOD=%)
        _p, _q = _tmp688*c, mag
        if not _q:
            raise ZeroDivisionError(repr(_tmp688*c) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                re = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                re = _p / _q
        else:
            re = _p / _q
        #RETURN_COMPLEX(REAL=re; IMAG=im)
        _tmp751 = new(cls)
        _tmp751.real = re
        _tmp751.imag = im
        return _tmp751
    if t is complex:
        #DIV_COMPLEX_COMPLEX(LHS=other; RHS=self; MOD=%)
        a, b = other.real, other.imag
        c, d = self.real, self.imag
        mag = c*c + d*d
        _tmp758 = b*c-a*d
        #DIV_VALUE_VALUE(LHS=a*c+b*d; RHS=mag; RESULT=re; MOD=%)
        _p, _q = a*c+b*d, mag
        if not _q:
            raise ZeroDivisionError(repr(a*c+b*d) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                re = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                re = _p / _q
        else:
            re = _p / _q
        if not _tmp758:
            return re
        #DIV_VALUE_VALUE(LHS=_tmp758; RHS=mag; RESULT=im; MOD=%)
        _p, _q = _tmp758, mag
        if not _q:
            raise ZeroDivisionError(repr(_tmp758) + " / " + repr(mag))
        #IF_CHECK_INT(T=type(_p))
        if type(_p) in inttypes_set:
            #IF_CHECK_INT(T=type(_q))
            if type(_q) in inttypes_set:
                #FRACTION_NORMALIZE(NUMER=_p; DENOM=_q; RNUMER=_rp; RDENOM=_rq; MOD=%)
                _rp = _x = _p
                _rq = _y = _q
                while _y:
                    _x, _y = _y, _x % _y
                if _x != 1:
                    _rp //= _x
                    _rq //= _x
                im = _rp if _rq == 1 else mpq((_rp, _rq))
            else:
                im = _p / _q
        else:
            im = _p / _q
        #RETURN_COMPLEX(REAL=re; IMAG=im)
        _tmp821 = new(cls)
        _tmp821.real = re
        _tmp821.imag = im
        return _tmp821
    return NotImplemented

def complex_pow(self, other, m=None, new=object.__new__, cls=mpqc):
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        if not other:
            return 1
        if other==1:
            return self
        if other==2:
            return self*self
        if other < 0:
            base, exponent = 1/self, -other
        else:
            base, exponent = self, other
        #POW_COMPLEX_INT(LHS=base; RHS=exponent; MOD=%)
        a, b = base.real, base.imag
        n = exponent
        if not a:
            case = n % 4
            if not case:
                return b**n
            elif case == 1:
                #RETURN_COMPLEX(REAL=0; IMAG=b**n)
                _tmp842 = new(cls)
                _tmp842.real = 0
                _tmp842.imag = b**n
                return _tmp842
            elif case == 2:
                return -(b**n)
            else:
                #RETURN_COMPLEX(REAL=0; IMAG=-b**n)
                _tmp849 = new(cls)
                _tmp849.real = 0
                _tmp849.imag = -b**n
                return _tmp849
        ta, tb = type(a), type(b)
        m = 1
        if ta is mpq:
            if tb is mpq:
                m = (a[1] * b[1]) ** n
                a, b = a[0]*b[1], a[1]*b[0]
            #ELIF_CHECK_INT(T=tb)
            elif tb in inttypes_set:
                m = a[1] ** n
                a, b = a[0], a[1]*b
        elif tb is mpq:
            #IF_CHECK_INT(T=ta)
            if ta in inttypes_set:
                m = b[1] ** n
                a, b = a*b[1], b[0]
        c, d = 1, 0
        while 1:
            if n & 1:
                c, d = a*c-b*d, b*c+a*d
                n -= 1
                if not n:
                    break
            a, b = a*a-b*b, 2*a*b
            n //= 2
        if m==1:
            #RETURN_COMPLEX2(REAL=c; IMAG=d)
            _tmp870 = d
            if not _tmp870:
                return c
            #RETURN_COMPLEX(REAL=c; IMAG=_tmp870)
            _tmp877 = new(cls)
            _tmp877.real = c
            _tmp877.imag = _tmp870
            return _tmp877
        # c,d,m are integers
        #FRACTION_NORMALIZE(NUMER=c; DENOM=m; RNUMER=re_p; RDENOM=re_q; MOD=%)
        re_p = _x = c
        re_q = _y = m
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            re_p //= _x
            re_q //= _x
        re = re_p if re_q==1 else mpq((re_p, re_q))
        if not d:
            return re
        #FRACTION_NORMALIZE(NUMER=d; DENOM=m; RNUMER=im_p; RDENOM=im_q; MOD=%)
        im_p = _x = d
        im_q = _y = m
        while _y:
            _x, _y = _y, _x % _y
        if _x != 1:
            im_p //= _x
            im_q //= _x
        if im_q==1:
            im = im_p
        else:
            im = mpq((im_p, im_q))
        #RETURN_COMPLEX(REAL=re; IMAG=im)
        _tmp898 = new(cls)
        _tmp898.real = re
        _tmp898.imag = im
        return _tmp898
    return NotImplemented
    
def fraction_lt(self, other, cls=mpq):
    p, q = self
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        return (p < q*other)
    elif t is cls:
        r, s = other
        return p*s < q*r
    return NotImplemented
    
def fraction_le(self, other, cls=mpq):
    p, q = self
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        return (p <= q*other)
    elif t is cls:
        r, s = other
        return p*s <= q*r
    return NotImplemented
    
def fraction_gt(self, other, cls=mpq):
    p, q = self
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        return (p > q*other)
    elif t is cls:
        r, s = other
        return p*s > q*r
    return NotImplemented
    
def fraction_ge(self, other, cls=mpq):
    p, q = self
    t = type(other)
    #IF_CHECK_INT(T=t)
    if t in inttypes_set:
        return (p >= q*other)
    elif t is cls:
        r, s = other
        return p*s >= q*r
    return NotImplemented
    
